---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Python3
  apt:
    name: python3
    state: present

- name: Install pip
  apt:
    name: python3-pip
    state: present

- name: Install boto3
  become: true
  pip:
    name: boto3
    state: present

- name: Install AWS CLI
  become: true
  pip:
    name: awscli
    state: latest
    executable: pip3

- name: Install Java 17 JDK
  apt:
    name: openjdk-17-jdk
    state: present

- name: Install NFS Client
  apt:
    name: nfs-common
    state: present

- name: Ensure mount directory exists
  file:
    path: "{{ efs_mount_dir }}"
    state: directory
    mode: 0755

- name: Ensure EFS volume is mounted
  mount:
    name: "{{ efs_mount_dir }}"
    src: "{{ efs_mount_point }}:/"
    fstype: nfs4
    opts: nfsvers=4.1
    state: mounted

- name: Add Jenkins apt repository key.
  ansible.builtin.get_url:
    url: "https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key"
    dest: /etc/apt/trusted.gpg.d/jenkins.asc
    mode: '0644'
    force: true

- name: Add Jenkins apt repository.
  apt_repository:
    repo: "deb https://pkg.jenkins.io/debian-stable binary/"
    state: present
    update_cache: true

- name: Install Jenkins
  apt:
    name: jenkins={{ jenkins_lts_version }}
    state: present

- name: Stop Jenkins service
  systemd:
    name: jenkins.service
    state: stopped

- name: Move Jenkins data to new directory
  copy: src=/var/lib/jenkins/ dest={{ jenkins_data_dir }} remote_src=yes directory_mode=yes

- name: Change directory owner
  file:
    path: "{{ jenkins_data_dir }}"
    owner: jenkins
    group: jenkins
    recurse: yes

- name: Remove old Jenkins data directory
  file:
    path: /var/lib/jenkins/
    state: absent

- name: Create override directory for Jenkins service
  become: true
  file:
    path: /etc/systemd/system/jenkins.service.d
    state: directory

- name: Add override file for Jenkins
  template:
    src: override.conf.j2
    dest: /etc/systemd/system/jenkins.service.d/override.conf
    owner: root
    group: root
    mode: '0644'

- name: Reload systemd daemon configuration
  systemd:
    daemon_reload: yes

- name: Start Jenkins Service
  systemd:
    name: jenkins
    state: started